# Filename: frontend/Dockerfile

# Use the official Nginx image from Docker Hub
FROM nginx:1.25-alpine

# Copy our custom index.html file to the Nginx public directory
COPY ./index.html /usr/share/nginx/html/index.html